apiVersion: v1
kind: ConfigMap
metadata:
  name: bankapp-config
  namespace: bankapp
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-statefulset-0.mysql-svc.bankapp.svc.cluster.local:3306/bankappdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"

---
apiVersion: v1
kind: Service
metadata:
  name: bankapp-svc
  namespace: bankapp
spec:
  selector:
    app: bankapp
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-deployment
  namespace: bankapp
  labels:
    app: bankapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      name: bankapp
      labels:
        app: bankapp
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-SPRING_DATASOURCE_USERNAME: "secret/data/frontend"
        vault.hashicorp.com/agent-inject-template-SPRING_DATASOURCE_USERNAME: |
          {{- with secret "secret/data/frontend" -}}
          export SPRING_DATASOURCE_USERNAME="{{ .Data.data.SPRING_DATASOURCE_USERNAME }}"
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-SPRING_DATASOURCE_PASSWORD: "secret/data/frontend"
        vault.hashicorp.com/agent-inject-template-SPRING_DATASOURCE_PASSWORD: |
          {{- with secret "secret/data/frontend" -}}
          export SPRING_DATASOURCE_PASSWORD="{{ .Data.data.SPRING_DATASOURCE_PASSWORD }}"
          {{- end }}
        vault.hashicorp.com/role: "vault-role"
    spec:
      securityContext:  
        runAsUser: 1000 
        runAsGroup: 3000  
        fsGroup: 2000
      serviceAccountName: vault-auth
      containers:
        - name: bankapp
          image: atkaridarshan04/bankapp:v2
          ports:
            - containerPort: 8000
          env:
            - name: VAULT_SECRETS_INIT
              value: "true"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: bankapp-config
                  key: SPRING_DATASOURCE_URL
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.25"
            limits:
              memory: "512Mi"
              cpu: "0.5"
          securityContext:  
            runAsUser: 1000 
            runAsGroup: 3000
            allowPrivilegeEscalation: false  
            capabilities:
              drop:
                - ALL 
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5